[package]
name = "ovfs"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.154"
futures = "0.3.30"
sharded-slab = "0.1.7"
opendal = { version = "0.46.0", features = ["services-fs"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
