name: OVFS Behavior Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Behavior Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Behavior Test
        env:
          KIND: fs
          ROOT: .github/scripts
        run: |
          cargo run --manifest-path ../../Cargo.toml  --release &
          chmod +x ./install_and_run_vm.sh
          ./install_and_run_vm.sh &
          pip install paramiko
          python behavior_test_judge.py
        working-directory: .github/scripts
